/**
 * ─────────────────────────────────────────────────────────────────
 *  ALL PORTFOLIO CONTENT LIVES HERE
 *  Edit this single file to update text, links, skills and projects.
 * ─────────────────────────────────────────────────────────────────
 */

// Email is stored in parts and joined at runtime (getEmail) so the full
// address never appears in the HTML or the JS bundle — keeps scrapers away.
// To change it, edit the two parts below.
export const emailParts = { user: "hello", domain: "mehedims.com" };
export const getEmail = () => `${emailParts.user}@${emailParts.domain}`;

export const profile = {
  name: "Mehedi Hasan",
  initials: "MH",
  role: "Web Developer & Support Engineer",
  tagline: "I build fast websites that stay fast.",
  // Your portrait — shown in the About section card.
  photo: "/profile.webp",
  availability: "Available for freelance projects",
  location: "Khulna, Bangladesh",
  phone: "+880 1957 594446",
  phoneHref: "+8801957594446",
  website: "mehedims.com",
  websiteUrl: "https://mehedims.com",
  // Generated by scripts/generate-cv.mjs — rerun after editing this file.
  cv: "/Mehedi-Hasan-CV.pdf",
};

export const hero = {
  eyebrow: "Web Developer · Support Engineer",
  headlineA: "I build fast websites",
  headlineB: "that stay fast.",
  sub: "Developer and technical support engineer from Khulna, Bangladesh — combining frontend craftsmanship with real WordPress, hosting and cloud operations experience, so sites stay reliable long after launch.",
  primaryCta: { label: "View my work", href: "#projects" },
  secondaryCta: { label: "Get in touch", href: "#contact" },
};

export const marqueeItems = [
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Go",
  "Tailwind CSS",
  "WordPress",
  "PHP · Laravel",
  "NGINX",
  "Caddy",
  "PowerDNS",
  "VPS Setup",
  "cPanel",
  "PostgreSQL · Redis",
  "LiteSpeed",
  "MySQL",
  "SEO",
];

export const about = {
  eyebrow: "About",
  title: "Development, backed by real operations.",
  paragraphs: [
    "I work at the intersection of web development, WordPress systems, hosting operations and practical user support. That means I don't just build responsive, understandable web systems — I improve existing sites so they remain reliable after launch.",
    "I value clear scope, careful delivery and responsive-by-default design. My goal is always to leave a project in a condition that clients and teams can confidently operate on their own afterward.",
  ],
  facts: [
    { label: "Based in", value: "Khulna, Bangladesh" },
    { label: "Current role", value: "Technical Support Engineer — Zorn Ventures Ltd." },
    { label: "Freelance since", value: "2021" },
    { label: "Focus", value: "WordPress performance · VPS & hosting · Frontend" },
  ],
  stats: [
    { value: 4, suffix: "+", label: "Years of experience" },
    { value: 15, suffix: "+", label: "Projects delivered" },
    { value: 2, suffix: "", label: "Hosting brands supported" },
  ],
};

export const skills = {
  eyebrow: "Skills",
  title: "One stack, floor to roof.",
  sub: "From the interface down to the server it runs on.",
  groups: [
    {
      title: "Frontend Development",
      blurb: "Interfaces that feel effortless on every screen.",
      items: ["React", "Next.js", "TypeScript", "Tailwind CSS", "UI Systems", "API Integration"],
    },
    {
      title: "Backend & Data",
      blurb: "Application logic that stays maintainable.",
      items: ["Node.js", "Go", "PHP", "Laravel", "Python", "MySQL", "PostgreSQL", "Redis"],
    },
    {
      title: "WordPress & CMS",
      blurb: "Speed-obsessed WordPress work — audits, caching, tuning.",
      items: ["WordPress", "LiteSpeed & Caching", "Performance Audits", "Ghost"],
    },
    {
      title: "Hosting & Servers",
      blurb: "Production servers and DNS infrastructure I actually operate myself.",
      items: ["NGINX · Caddy", "PowerDNS", "VPS Setup", "Ubuntu · AlmaLinux · Debian", "cPanel · CloudPanel · WHMCS", "AWS · Azure · DigitalOcean · Linode"],
    },
    {
      title: "Performance & Growth",
      blurb: "Measurable outcomes, not just clean code.",
      items: ["Web Performance", "Core Web Vitals", "SEO", "Technical Support"],
    },
    {
      title: "Ways of Working",
      blurb: "How projects run smoothly end to end.",
      items: ["Clear Scope", "Careful Delivery", "Documentation", "Project Handoff"],
    },
  ],
};

export const projects = {
  eyebrow: "Selected Work",
  title: "Work that survives launch day.",
  sub: "Platforms, marketplaces and stores — designed, built or rescued.",
  items: [
    {
      name: "Tools.BD",
      kind: "Network & Domain Tools",
      category: "Web Platform",
      year: "2026",
      description:
        "A free suite of network utilities — analyse any domain's DNS, WHOIS and email security, or look up ASN, IP address and network prefix details. Instantly. Built on Go with PostgreSQL, Redis and SSE streaming behind Caddy.",
      tags: ["Go", "miekg/dns", "PHP", "PostgreSQL + Redis", "SSE", "Caddy"],
      link: "https://tools.bd/",
      shot: "/screens/bd-tools.jpg",
      gradient: "from-[#0071e3] via-[#4a6cf7] to-[#7d4bff]",
    },
    {
      name: "AsiaBio Link",
      kind: "URL Shortener",
      category: "Full-stack",
      year: "2026",
      description:
        "Clinical precision in URL management — a fast, reliable link shortener built for developers, digital marketers and power users. Built in Laravel.",
      tags: ["Laravel", "URL Shortener", "Analytics"],
      link: "https://asiabio.link/",
      shot: "/screens/asiabio-link.jpg",
      gradient: "from-[#8b5cf6] via-[#a78bfa] to-[#c4b5fd]",
    },
    {
      name: "BuyAPet UK",
      kind: "Pet Classifieds Marketplace",
      category: "WordPress",
      year: "2025",
      description:
        "The UK's fast-growing pet classifieds — puppies, kittens and more. I handled theme updates and speed optimization so browsing stays snappy across hundreds of listings.",
      tags: ["WordPress", "Speed Optimization", "SEO"],
      link: "https://buyapet.co.uk/",
      shot: "/screens/buyapet.jpg",
      gradient: "from-[#ff8a00] via-[#ff6a3d] to-[#ee5253]",
    },
    {
      name: "CodeXSell",
      kind: "Digital Products Marketplace",
      category: "Full-stack",
      year: "2026",
      description:
        "A GPL WordPress marketplace with 1800+ themes and plugins, membership tiers, download quotas and an auto-updater — the full system, admin panel included, built in Laravel.",
      tags: ["Laravel", "PHP", "Admin Panel", "Memberships"],
      link: "https://codexsell.com/",
      shot: "/screens/codexsell.jpg",
      gradient: "from-[#7c5cff] via-[#a855f7] to-[#ec4899]",
    },
  ],
  moreProjects: [
    {
      name: "Zeely Realty",
      kind: "Real Estate Platform",
      category: "Full-stack",
      year: "2026",
      description:
        "A buy-and-rent real estate broker platform — property listings, broker workflow and search, built as a complete Laravel system from the ground up.",
      tags: ["Laravel", "PHP", "MySQL", "Listings"],
      link: "https://zeelyrealty.com/",
      shot: "/screens/zeely-realty.jpg",
      gradient: "from-[#0ea5e9] via-[#22d3ee] to-[#5eead4]",
    },
    {
      name: "Diploma ICU",
      kind: "Student Blog & Resources",
      category: "WordPress",
      year: "2024",
      description:
        "A blog for Bangladeshi students — I built the custom WordPress theme and wrote student-focused content to grow the audience.",
      tags: ["WordPress", "Theme Development", "Content"],
      link: "https://diploma.icu/",
      shot: "/screens/diploma-icu.jpg",
      gradient: "from-[#10b981] via-[#34d399] to-[#a7f3d0]",
    },
    {
      name: "Saajkonna",
      kind: "Beauty E-commerce — Speed",
      category: "Performance",
      year: "2023",
      description:
        "A WooCommerce beauty store with 100+ brands and nationwide delivery in Bangladesh — I optimized it end to end, and it now loads fast.",
      tags: ["WordPress", "WooCommerce", "Speed Optimization"],
      link: "https://saajkonna.com/",
      shot: "/screens/saajkonna.jpg",
      gradient: "from-[#f43f5e] via-[#fb7185] to-[#fda4af]",
    },
    {
      name: "PowerDNS Cluster",
      kind: "DNS Infrastructure",
      category: "Infrastructure",
      year: "2026",
      description:
        "A redundant PowerDNS cluster with API access powering DNS for the hosting brands — built for high availability, fast propagation and easy automation.",
      tags: ["PowerDNS", "High Availability", "Linux", "API"],
      link: "#",
      gradient: "from-[#0ea5e9] via-[#38bdf8] to-[#7dd3fc]",
    },
    {
      name: "WHMCS PowerDNS PTR Manager",
      kind: "WHMCS Module",
      category: "WHMCS",
      year: "2026",
      description:
        "A WHMCS module that lets users and admins easily manage PTR records and rDNS blocks — self-service PTR management wired straight into the PowerDNS cluster.",
      tags: ["WHMCS", "PowerDNS", "PHP", "rDNS"],
      link: "#",
      gradient: "from-[#8b5cf6] via-[#818cf8] to-[#a5b4fc]",
    },
    {
      name: "WHMCS PowerDNS DNS Manager",
      kind: "WHMCS Module",
      category: "WHMCS",
      year: "2026",
      description:
        "Full DNS zone management inside WHMCS for customers who buy domains on the platform — records, zones and propagation, all self-service.",
      tags: ["WHMCS", "PowerDNS", "Domains", "PHP"],
      link: "#",
      gradient: "from-[#10b981] via-[#2dd4bf] to-[#99f6e4]",
    },
    {
      name: "WHMCS Easy Product Transfer",
      kind: "WHMCS Module",
      category: "WHMCS",
      year: "2026",
      description:
        "One-click transfer of any product or service between WHMCS clients — moving hosting, domains and services without support tickets.",
      tags: ["WHMCS", "PHP", "Automation"],
      link: "#",
      gradient: "from-[#f59e0b] via-[#fbbf24] to-[#fde68a]",
    },
  ],
  more:
    "…plus 15+ full-stack applications and responsive websites delivered for a global client base on Upwork & Fiverr.",
};

export const experience = {
  eyebrow: "Experience",
  title: "Where I've worked.",
  items: [
    {
      company: "Zorn Ventures Limited",
      role: "Technical Support Engineer",
      period: "May 2026 — Present",
      current: true,
      summary:
        "Supporting the SatisfyHost and BengalCloud brands — helping customers resolve hosting and cloud-service issues through clear, dependable technical guidance.",
      points: [
        "Hosting & cloud troubleshooting across VPS, cPanel and custom PowerDNS infrastructure",
        "Built and operate a redundant PowerDNS cluster for the SatisfyHost and BengalCloud brands",
        "Developed WHMCS modules — PowerDNS PTR & DNS managers and easy product transfer",
        "Clear, reproducible communication that turns tickets into solutions",
      ],
    },
    {
      company: "TechZ IT",
      role: "Chief Information Officer",
      period: "2025",
      summary:
        "Led overall IT strategy, infrastructure management and digital transformation initiatives to improve system performance, security and scalability.",
      points: [
        "Oversaw development teams and technology operations",
        "Ensured efficient project delivery, cloud integration and alignment with business goals",
        "Directed infrastructure upgrades that improved security, uptime and scalability",
        "Led digital transformation initiatives across the company's service lines",
      ],
    },
    {
      company: "Independent · Upwork & Fiverr",
      role: "Freelance Web Developer",
      period: "2021 — Present",
      current: true,
      summary:
        "Delivering responsive websites, custom interfaces and technical improvements for remote clients worldwide.",
      points: [
        "15+ full-stack web applications and sites using Next.js, Laravel and React",
        "Architected a comprehensive academic ERP with Python and MySQL",
        "Specialised in WordPress speed optimisation and robust VPS management",
        "Launched my own products end to end — from Tools.BD network utilities to Laravel SaaS platforms",
      ],
    },
  ],
};

export const education = {
  eyebrow: "Education",
  title: "Always studying the craft.",
  degree: {
    school: "Mangrove Institute of Science and Technology",
    degree: "Diploma in Engineering — Computer Science Technology",
    period: "2023 — 2027 (expected)",
    courses: [
      "Data Structures & Algorithms",
      "Web Development",
      "Database Management Systems",
      "Operating Systems",
      "Computer Networks",
      "Software Engineering",
      "Object-Oriented Programming",
      "Cyber Security",
    ],
  },
  certification: {
    authority: "National Skills Development Authority (NSDA)",
    title: "Web Design and Development for Freelancing — Level 3",
    period: "Result published December 2025",
    note: "Client communication · JavaScript development · CSS frameworks · ICT ethics",
  },
  languages: [
    { name: "Bengali", level: "Native proficiency" },
    { name: "English", level: "Professional working proficiency" },
  ],
};

export const writing = {
  eyebrow: "Notes",
  title: "Writing & notes on craft.",
  items: [
    {
      title: "WordPress performance audits",
      excerpt:
        "How I audit a slow WordPress site — and the caching, asset and server decisions that actually move the needle.",
    },
    {
      title: "Reproducible support questions",
      excerpt:
        "The exact information that turns a vague 'it doesn't work' into a solvable ticket in one reply.",
    },
    {
      title: "Smoother project handoffs",
      excerpt:
        "Leaving projects in a condition clients and teams can confidently operate afterward — docs, access and decisions.",
    },
  ],
};

export const contact = {
  eyebrow: "Contact",
  title: "Let's build something reliable.",
  sub: "I'm available for freelance projects — from fast marketing sites to full-stack builds and WordPress / VPS optimisation. Tell me what you're working on.",
  socials: [
    { label: "GitHub", href: "https://github.com/asma019" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/mehedims1/" },
    { label: "Upwork", href: "https://upwork.com/freelancers/~01f39b319379efc4d6" },
    { label: "Fiverr", href: "https://www.fiverr.com/mehedims1" },
  ],
};

export const navLinks = [
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Work", href: "#projects" },
  { label: "Experience", href: "#experience" },
  { label: "Education", href: "#education" },
  { label: "Contact", href: "#contact" },
];
